"""Configuration for the collaborative whiteboard."""

from libp2p.custom_types import TProtocol

DEFAULT_LIBP2P_PORT = 8001
DEFAULT_WS_BRIDGE_PORT = 8766
DATA_DIR = "./whiteboard_data"

GOSSIPSUB_PROTOCOL_ID = TProtocol("/meshsub/1.1.0")
SYNC_PROTOCOL_ID = TProtocol("/whiteboard/sync/1.0.0")

TOPIC_PREFIX = "/collab/whiteboard/"
DEFAULT_BOARD_ID = "default"

MAX_SHAPES = 10000
MAX_STROKE_POINTS = 1000

MSG_DRAW = "DRAW"
MSG_CLEAR = "CLEAR"
MSG_DELETE_SHAPE = "DELETE_SHAPE"
MSG_FULL_STATE = "FULL_STATE"
MSG_SYNC_REQUEST = "SYNC_REQUEST"
MSG_SYNC_RESPONSE = "SYNC_RESPONSE"
MSG_CURSOR = "CURSOR"
MSG_PEER_JOIN = "PEER_JOIN"
MSG_PEER_LEAVE = "PEER_LEAVE"

SHAPE_STROKE = "stroke"
SHAPE_RECT = "rect"
SHAPE_CIRCLE = "circle"
SHAPE_LINE = "line"

GOSSIPSUB_DEGREE = 6
GOSSIPSUB_DEGREE_LOW = 4
GOSSIPSUB_DEGREE_HIGH = 8
GOSSIPSUB_HEARTBEAT_INTERVAL = 1
GOSSIPSUB_HEARTBEAT_INITIAL_DELAY = 0.5
GOSSIPSUB_TIME_TO_LIVE = 60
GOSSIPSUB_GOSSIP_WINDOW = 3
GOSSIPSUB_GOSSIP_HISTORY = 5