"""Configuration for the collaborative notepad."""

from libp2p.custom_types import TProtocol

DEFAULT_LIBP2P_PORT = 8000
DEFAULT_WS_BRIDGE_PORT = 8765
DATA_DIR = "./notepad_data"

GOSSIPSUB_PROTOCOL_ID = TProtocol("/meshsub/1.1.0")
SYNC_PROTOCOL_ID = TProtocol("/notepad/sync/1.0.0")

TOPIC_PREFIX = "/collab/notepad/"
DEFAULT_DOC_ID = "default"

MAX_DOC_SIZE = 500_000
OP_BATCH_INTERVAL = 0.05

MSG_INSERT = "INSERT"
MSG_DELETE = "DELETE"
MSG_FULL_STATE = "FULL_STATE"
MSG_SYNC_REQUEST = "SYNC_REQUEST"
MSG_SYNC_RESPONSE = "SYNC_RESPONSE"
MSG_CURSOR = "CURSOR"
MSG_PEER_JOIN = "PEER_JOIN"
MSG_PEER_LEAVE = "PEER_LEAVE"

GOSSIPSUB_DEGREE = 6
GOSSIPSUB_DEGREE_LOW = 4
GOSSIPSUB_DEGREE_HIGH = 8
GOSSIPSUB_HEARTBEAT_INTERVAL = 1
GOSSIPSUB_HEARTBEAT_INITIAL_DELAY = 0.5
GOSSIPSUB_TIME_TO_LIVE = 60
GOSSIPSUB_GOSSIP_WINDOW = 3
GOSSIPSUB_GOSSIP_HISTORY = 5
